# Configuration settings for FileUtils

csv_delimiter: ","
encoding: "utf-8"
quoting: 0  # csv.QUOTE_MINIMAL
include_timestamp: true
logging_level: "DEBUG"
disable_logging: false

# Directory structure
directory_structure:
  data:
    - raw
    - interim
    - processed
  reports:
    - figures
    - outputs
  models: []
  src:
    - scripts
    - notebooks

# File format settings
parquet_compression: "snappy"

# Azure Storage settings (optional)
azure:
  enabled: false  # Set to true to enable Azure storage
  container_mapping:
    raw: "raw-data"
    processed: "processed-data"
    interim: "interim-data"
    parameters: "parameters"
    configurations: "configurations"
  retry_settings:
    max_retries: 3
    retry_delay: 1
  connection_string: ""  # Set via environment variable