name: fileutils
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip>=19.0
  # Core dependencies
  - pandas>=1.3.0
  - pyyaml>=5.4.1
  - python-dotenv>=0.19.0
  - jsonschema>=3.2.0
  # Optional dependencies
  - azure-storage-blob>=12.0.0
  - azure-identity>=1.5.0
  - pyarrow>=7.0.0
  - openpyxl>=3.0.9
  # Development dependencies
  - pytest>=6.0
  - black
  - isort
  - mypy
  - flake8
  - pre-commit
  - jupyter
  - pip:
      - git+ssh://git@github.com/topij/FileUtils.git#egg=FileUtils[all]