name: fileutils
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip>=19.0
  # Core dependencies
  - pandas>=1.3.0
  - pyyaml>=5.4.1
  - python-dotenv>=0.19.0
  - jsonschema>=3.2.0
  # Optional dependencies
  - azure-storage-blob>=12.0.0
  - azure-identity>=1.5.0
  - pyarrow>=7.0.0
  - openpyxl>=3.0.9
  # Document dependencies (via pip)
  - pip
  - pip:
    - python-docx>=0.8.11
    - markdown>=3.4.0
    - PyMuPDF>=1.23.0
  # Development dependencies
  - black
  - isort
  - mypy
  - flake8
  - pre-commit
  # Testing
  - pytest>=6.0.0
  - pytest-cov>=4.1.0
  - pytest-asyncio>=0.21.0
  - pytest-mock>=3.11.1
  # Build tools
  - build
  - twine
  - wheel
  # Documentation
  - mkdocs
  - mkdocs-material
  # Development
  - jupyter
  - ipython
  - ipykernel
  