# Example configuration for Customer Success documentation workflow
# This demonstrates how to customize directory names for domain-specific projects

# Directory configuration
directories:
  # Use "documents" instead of "data" for document-focused projects
  data_directory: "documents"
  
  # Customize subdirectory names if needed
  subdirectories:
    raw: "raw"           # Product documentation
    processed: "processed"  # CS plans and documents
    templates: "templates"  # DOCX templates

# Standard FileUtils configuration
csv_delimiter: ";"
encoding: "utf-8"
quoting: 0  # csv.QUOTE_MINIMAL
include_timestamp: true
logging_level: "INFO"

# Legacy directory structure (for backward compatibility)
directory_structure:
  data:
    - raw
    - processed
    - templates
  reports:
    - figures
    - outputs
    - tables
  models: []
  src: []

logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file_logging: false
  log_directory: "logs"

storage:
  default_type: "local"
  azure:
    enabled: false
    container_mapping:
      raw: "raw-data"
      processed: "processed-data"
      interim: "interim-data"
      parameters: "parameters"
      configurations: "configurations"
    retry_settings:
      max_retries: 3
      retry_delay: 1
      max_delay: 30
