# src/FileUtils/config/default_config.yaml

csv_delimiter: ";"
encoding: "utf-8"
quoting: 0  # csv.QUOTE_MINIMAL
include_timestamp: true
logging_level: "INFO"

directory_structure:
  data:
    - raw
    - interim
    - processed
    - external
    - configurations
  reports:
    - figures
    - outputs
    - tables
  models: []
  src: []


logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file_logging: false
  log_directory: "logs"

storage:
  default_type: "local"
  azure:
    enabled: false
    container_mapping:
      raw: "raw-data"
      processed: "processed-data"
      interim: "interim-data"
      parameters: "parameters"
      configurations: "configurations"
    retry_settings:
      max_retries: 3
      retry_delay: 1
      max_delay: 30