# Default configuration for FileUtils

# Basic settings
csv_delimiter: ";"
encoding: "utf-8"
quoting: 0  # csv.QUOTE_MINIMAL
include_timestamp: true
logging_level: "INFO"
disable_logging: false

# File format settings
parquet_compression: "snappy"
excel_engine: "openpyxl"

# Directory structure
directory_structure:
  data:
    - raw
    - interim
    - processed
    - external
    - configurations
  reports:
    - figures
    - outputs
    - tables
  models:
    - trained
    - evaluations
  src:
    - scripts
    - notebooks

# Logging configuration
logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file_logging: false
  log_directory: "logs"

# Azure Storage settings (optional)
azure:
  enabled: false
  container_mapping:
    raw: "raw-data"
    processed: "processed-data"
    interim: "interim-data"
    parameters: "parameters"
    configurations: "configurations"
  retry_settings:
    max_retries: 3
    retry_delay: 1
    max_delay: 30
  connection_string: ""  # Set via environment variable

# Error handling settings
error_handling:
  raise_on_missing_file: true
  strict_type_checking: true
  auto_create_directories: true